Add start message, add proxy
lip-salve/great_party_bot pull request #1
Opened 2020-01-10 08:36 UTC by beaulirl

2020-01-10 10:08 UTC, zdrasteenastya requested changes
Code changes looks good to me.

Please add the requirements.txt file

2020-01-10 10:08 UTC, zdrasteenastya commented on .gitignore
> +__*
Please add the newline at end of file

2020-01-13 11:30 UTC, beaulirl commented on .gitignore
> +__*
Done

2020-01-13 11:36 UTC, zdrasteenastya approved these changes

2020-01-13 11:41 UTC, merged